import JSZip from 'jszip';
import {
  Workspace,
  Message,
  Task,
  Attachment,
  ProjectState,
  FilterReport,
  AIAccount,
  ArchiveManifest,
} from '../types/index.ts';

export function buildArchiveManifest(params: {
  workspace: Workspace;
  messages: Message[];
  tasks: Task[];
  attachments: Attachment[];
  accounts: AIAccount[];
}): ArchiveManifest {
  const { workspace, messages, tasks, attachments, accounts } = params;

  const participantIds = Array.from(
    new Set([
      workspace.managerAccountId,
      workspace.backupManagerAccountId,
      workspace.callerAccountId,
      workspace.filterAccountId,
      ...workspace.workerAccountIds,
      ...messages.map((m) => m.senderId),
    ])
  ).filter((id): id is string => Boolean(id) && id !== 'USER');

  const participants = participantIds.map((id) => {
    const acc = accounts.find((a) => a.id === id);
    let role = 'Worker';
    if (id === workspace.managerAccountId) role = 'Active Manager';
    else if (id === workspace.backupManagerAccountId) role = 'Backup Manager';
    else if (id === workspace.callerAccountId) role = 'Caller';
    else if (id === workspace.filterAccountId) role = 'Filter';

    return {
      id,
      name: acc?.canonicalName || id,
      role,
      provider: acc?.providerId || 'Unknown',
      status: acc?.connectionStatus || 'NOT_CONNECTED',
    };
  });

  return {
    archiveVersion: '1.0.0',
    exportedAt: new Date().toISOString(),
    workspaceId: workspace.id,
    workspaceName: workspace.name,
    objective: workspace.objective,
    totalEvents: messages.length,
    totalMessages: messages.length,
    totalTasks: tasks.length,
    totalFiles: attachments.length,
    participants,
    fileList: attachments.map((a) => ({
      id: a.id,
      name: a.name,
      type: a.fileType,
      size: a.formattedSize,
    })),
  };
}

export async function exportProjectArchiveZip(params: {
  workspace: Workspace;
  messages: Message[];
  tasks: Task[];
  attachments: Attachment[];
  projectState?: ProjectState;
  filterReports?: FilterReport[];
  accounts: AIAccount[];
}): Promise<Blob> {
  const { workspace, messages, tasks, attachments, projectState, filterReports, accounts } = params;

  const zip = new JSZip();

  // 1. Manifest
  const manifest = buildArchiveManifest({
    workspace,
    messages,
    tasks,
    attachments,
    accounts,
  });
  zip.file('manifest.json', JSON.stringify(manifest, null, 2));

  // 2. Structured messages and chronological history
  const archiveEvents = messages.map((m, index) => ({
    eventIndex: index + 1,
    id: m.id,
    timestamp: m.timestamp,
    sender: {
      id: m.senderId,
      name: m.senderName,
      type: m.senderType,
      accountIdentity: m.accountIdentity || m.senderName,
      provider: m.provider,
    },
    recipient: m.recipientName ? { id: m.recipientId, name: m.recipientName } : null,
    taskId: m.taskId || null,
    messageType: m.messageType,
    isInternalWorkforce: m.isInternalWorkforce,
    content: m.content,
    attachments: m.attachments.map((a) => ({
      id: a.id,
      name: a.name,
      type: a.fileType,
      size: a.formattedSize,
    })),
  }));
  zip.file('messages_and_events.json', JSON.stringify(archiveEvents, null, 2));

  // 3. Tasks
  zip.file('tasks.json', JSON.stringify(tasks, null, 2));

  // 4. Project State
  if (projectState) {
    zip.file('project_state.json', JSON.stringify(projectState, null, 2));
  }

  // 5. Filter Reports
  if (filterReports && filterReports.length > 0) {
    zip.file('filter_reports.json', JSON.stringify(filterReports, null, 2));
  }

  // 6. Original Artifacts & Files folder
  const artifactsFolder = zip.folder('artifacts');
  if (artifactsFolder) {
    attachments.forEach((att) => {
      const fileContent = att.contentPreview || `// Content for ${att.name}\n// Generated by: ${att.creatorName || 'AI'}\n// Size: ${att.formattedSize}`;
      artifactsFolder.file(att.name, fileContent);
    });
  }

  // 7. Human-readable README
  const readmeText = `================================================================================
AI CHAT — COMPLETE PROJECT ARCHIVE
Workspace: ${workspace.name}
Objective: ${workspace.objective}
Export Date: ${new Date().toLocaleString()}
Archive Version: 1.0.0
================================================================================

This archive represents the immutable, chronological history of this workforce project.

INCLUDED RECORDS:
1. manifest.json           - Manifest and catalog of all participants and files
2. messages_and_events.json - Complete chronological event sequence with full identity attribution
3. tasks.json              - All tasks with states (QUEUED, ASSIGNED, WORKING, COMPLETED, etc.)
4. project_state.json      - Current synthesis of completed work, active decisions, and next steps
5. filter_reports.json     - Structured workforce reports produced by the Filter AI
6. artifacts/              - Directory of all original code, CSV, schemas, and documents produced

PARTICIPATING AI WORKFORCE:
${manifest.participants.map((p) => `- [${p.role}] ${p.name} (Provider: ${p.provider})`).join('\n')}

All original sender identities, message timestamps, and task correlations are preserved.
================================================================================
`;
  zip.file('README.txt', readmeText);

  return await zip.generateAsync({ type: 'blob' });
}

export function downloadBlobAsFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
